/*
 * Copyright (C) 2021 by the Widelands Development Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

#include <string>
#include <vector>

static const std::vector<std::string> formats_str = {
"ABORTING. Unable to find map object for '%s'!\n",
"ActConstruct: immovable '%s' does not exist",
"act: %s",
"Adding directory: %s\n",
"┃    Add-On ‘%s’",
"Add-on '%s' not found",
"Add-on %s required by host not found",
"A file with the name ‘%s’ already exists. Overwrite?",
"AI: Max preciousness must not be <= 0 for building: %s",
"Alternatively, you can access it directly with the ‘%s’ key.",
"Animals: %s",
"A reed yard can produce a sheaf of reed in about %s on average.",
"Are you sure you want to kick %s?",
"Author: %s",
"Autosave: Deleted %s\n",
"Autosave: ERROR! - %s\n",
"Autosave: saving as %s\n",
"Back to ‘%s’",
"Backup file ‘%s’ could not be deleted.",
"Backup file ‘%s’ will be available for some time.",
"battle: %s",
"[BufferedConnection] Connection to %s.",
"   Building name    %s",
"by %s",
"call economy balance: %s",
"   can_act_         %7s",
"Caps: %s",
"Category: %s",
"Clicking button '%s'\n",
"Clicking tab '%s'\n",
"Client sent malformed commands: %s",
"Client %s is cheating!",
"Closing window '%s'\n",
"Completed %s",
"contact error: %s",
"Could not create %s shader.",
"could not load \"%s\"",
"Could not read locale fontset for: %s\n",
"Could not read locale for: %s\n",
"Could not read locales fontset information from file: %s\n",
"Could not read locales information from file: %s\n",
"could not save configuration: %s\n",
"could not save training wheels: %s\n",
"count_all_dependencies: '%s' not installed",
"Created constructionsite for a %s, which is not of any known building type\n",
"Current directory: %s",
"Current: %s …",
"Current: %s",
"Default template directory '%s' does not exist!",
"Delete syncstream or replay %s\n",
"Deleting generated ai file: %s\n",
"Deleting old temp backup file: %s\n",
"Deleting old temp file: %s\n",
"Deprecated enhancement code found in building '%s'",
"Deprecated enhancement_cost code found in building '%s'",
"Deprecated usage in %s. Please convert playsound's 'priority' option to ",
"Description: %s",
"Directory ‘%s’ could not be created!",
"Done running %s.",
"Downloading ‘%s’…",
"Do you really want to commit all changes to the add-on ‘%s’ to disk?",
"Do you really want to delete the add-on ‘%s’?",
"Do you really want to delete the directory ‘%s’ and all its contents?",
"Do you really want to delete the map ‘%s’?",
"Do you really want to discard all changes to the add-on ‘%s’?",
"Do you really want to sink %s?",
"Do you really want to upload the add-on ‘%s’ to the server?",
"Economy::create_requested_worker: buildcost inconsistency '%s'",
"Emergency save failed because: %s",
"Empty helptext defined for '%s'",
"Empty value of command line parameter: %s",
"Enabled Add-Ons: %s",
"Enhance to %s",
"Error allocating game: %s",
"Error in animation table: %s",
"Error linking:\n%s",
"Error loading script for editor help:\n%s\n",
"Error loading script for encyclopedia:\n%s\n",
"Error parsing datadir: %s\n",
"Error: %s",
"ERROR: %s",
"Error trying to fetch Arabic character form: %s\n",
"Error trying to fetch Arabic diacritic form: %s\n",
"Error while creating directory ‘%s’.",
"Error writing data to file ‘%s’!",
"Exception: %s.\n",
"Failed to initialize SDL, no valid video driver: %s",
"Failed to initialize sound system: %s\n",
"Failed to load the minimap image: %s",
"Failed to load the minimap image : %s\n",
"Failed to save game for replay: %s",
"Failed to write into zipfile %s",
"Fastplace defaults: Unused key '%s'",
"Fatal exception: %s\n",
"Filename may not contain ‘%s’",
"File name '%s' is not allowed in scenario tribes – expecting ",
"File ‘%s’ could not be removed!",
"File ‘%s’ could not be restored!",
"File ‘%s’ was restored from backup.",
"Found deprecated 'pictures' parameter in animation with file\n   %s\n",
"Game not started: Game data error: %s\n",
"Gametime: %s",
"Graphics: OpenGL: ShadingLanguage: \"%s\"\n",
"Graphics: OpenGL: Version \"%s\"\n",
"   has_priority_    %7s",
"Help: %s",
"Helptexts script for %s is obsolete - please move strings to ",
"Hint: %s",
"Host sent player %s to the lobby!",
"ID:            %s\n",
"If yes, type: /ack_kick %s",
"If you wish to help us translate, please visit %s",
"Ignoring malformed add-ons config substring '%s'\n",
"Ignoring malformed fastplace config string: %s",
"Image not found: %s",
"ImmovableActionData::load: type %s not known",
"Immovable: %s",
"immovable type: %s",
"Incompatible: %s",
"incorporate: %s",
"install addon %s cancelled by user",
"install translations for %s cancelled by user",
"InternetGaming: Client announced the start of the game %s.",
"InternetGaming: Client opened a game with the name %s.",
"InternetGaming: Client tries to join a game with the name %s",
"InternetGaming: Error: %s\n",
"InternetGaming: logout(%s)",
"InternetGaming: Password check successful at UTC %s",
"InternetGaming: Received %s cmd although client is not in CONNECTING state.\n",
"InternetGaming: Strange ERROR in connecting state: %s\n",
"Invalid add-on category '%s'",
"Invalid chat message type \"%s\".",
"Invalid map file '%s'",
"invalid MapGenBobCategory %s",
"Invalid path to file in campaigns.lua of tutorials.lua: %s",
"Invalid richtext: %s",
"Invalid soldier preference '%s'",
"invalid syntax: %s",
"invalid tribe ‘%s’",
"Invalid ware priority '%s'",
"Is: %s",
"key %s outside section",
"Kicked by the host: %s",
"[LAN] Will broadcast to %s.",
"LayeredFileSystem: No writable filesystem for dir: %s!",
"LayeredFileSystem: No writable filesystem for %s!",
"LayeredFileSystem: unable to create sub filesystem for new directory: %s",
"Loading Battle: %s",
"loading bob: %s",
"loading carrier: %s",
"loading critter: %s",
"loading ferry fleet: %s",
"loading ferry: %s",
"Loading map “%s”…",
"loading player immovable: %s",
"loading portdock: %s",
"┏━ Loading %s",
"loading ship fleet: %s",
"loading shipping schedule: %s",
"loading ship: %s",
"loading soldier: %s",
"loading worker: %s",
"Logged in as %s",
"Logged in as %s (admin)",
"Manually running training wheel '%s'",
"MapAllowedBuildingTypesPacket - tribe %s does not define ",
"Map::get_correct_loader: File error: %s\n",
"Map::get_correct_loader: Unknown error: %s\n",
"map object: %s",
"Map: %s",
"Mapselect: Skip %s due to unknown exception\n",
"Map '%s' is both balanced and unbalanced - please fix the 'elemental' ",
"missing ']' after \"%s\"",
"       Name         %s",
"Name: %s",
"\n\n=========================\nWriting tribe: %s\n=========================\n",
"No backgrounds found for theme '%s', using fallback image",
"No helptext defined for '%s'",
"No locale translations found in %s\n",
"Not enough space to draw spinbox \"%s\".\n",
"Not loading add-on '%s' (not found)\n",
"Not loading add-on '%s' (wrong file name extension)\n",
"Old-style syntax found for 'construct' program in %s, use ",
"Opening dropdown '%s'\n",
"plan_workers: bad buildcost '%s'",
"player-requested file deletion failed: %s",
"Players: %s",
"preload_addon (%s): category is None",
"preload_addon (%s): version string is empty",
"Pressing button '%s'\n",
"Press ‘%s’ to quickly toggle the display of your stock inventory.",
"Produced %s",
"productionsite has failed/skipped program \"%s\", which ",
"productionsite has unknown program \"%s\", replacing it with ",
"Realpath: %s\n",
"Received an unknown command from the metaserver: %s",
"Received command number %s, which is not allowed in this state.",
"Recruited %s",
"Registry file %s does not define any units",
"Replace player with %s",
"REPLAY: Caught exception %s\n",
"request: %s",
"requirements: %s",
"Requires a Widelands version of at least %s.",
"Requires a Widelands version of at most %s.",
"Running postload script for add-on %s",
"Running preload script for add-on %s",
"Running training wheel '%s'",
"Running training wheels. Current active is %s",
"  -> %s",
" %s",
" -> %s",
"%s",
"%s(",
"%s:",
"(%s)",
"· %s",
"“%s”",
"%s and",
"%s anywhere in the filename",
"%s apparently not a valid replay file",
"%s are missing",
"%s at the start of the filename",
"Saved: %s",
"Save handler returned error: %s",
"Save screenshot to %s\n",
"%s can not be combined with other actions",
"Scenario not started: Game data error: %s\n",
"Script requests save to: %s\n",
"Script %s not found.",
"%s: Deprecated 'bob' in 'transform' program, use 'bob:<name>' instead.\n",
"%s: Deprecated chance in 'remove' program, use 'chance:<percent>' instead.\n",
"%s: Deprecated chance in 'transform' program, use 'chance:<percent>' ",
"SDL_GL_LoadLibrary failed: %s",
"selected language: %s\n",
"Selecting current item in dropdown '%s'\n",
"Set configuration file: %s",
"Set home directory: %s\n",
" - Set LANGUAGE, LANG and LC_ALL to '%s'\n",
"set_login (''): server error (%s)",
" - Set system locale to 'en_US.utf8' to make '%s' accessible to libintl\n",
"set_template_dir: template directory '%s' does not exist, using default template",
"%s has joined the game",
"%s has no animation assigned for its representative image, or it's not a known ",
"%s has not been saved",
"%s has won the game. Congratulations!",
"Ships: %s",
"Shortcut '%s' does not exist",
"   show_only_       %7s",
"%s is a replay from a version that is known to have desync ",
"%s is missing",
"%s is not a directory. Please fix this.\n",
"Size: %s",
"%s joined the lobby",
"Skipped CmdSetInputMaxFill command: %s",
"Skipped running training wheel '%s'",
"Skipping training wheel '%s'",
"%s left the lobby",
"%s lost control of the hill.",
"%s (missing)",
" [%s]\n",
"%s\n",
"*** %s\n",
"Solved training wheel '%s'",
"Something went wrong: %s",
"Songset: Loaded song \"%s\"\n",
"Songset: Loading song \"%s\" failed!\n",
"Songset: %s\n",
"%s or better",
"SoundHandler: Audio error %s\n",
"SoundHandler: Mix_PlayChannel failed: %s\n",
"SoundHandler: SDL_AUDIODRIVER %s\n",
"SoundHandler: songset \"%s\" does not exist!\n",
"%s owns more than half of the map’s area.",
"Starting to lock mutex %s (run_while_waiting) ...",
"Status for %s",
"%s: The 'collects_ware_from_map' key in 'ai_hints' is no longer used",
"%s: The 'mines' key in 'ai_hints' is no longer used",
"%s: The 'supports_production_of' key in 'ai_hints' is no longer used",
"   Stopped          %7s",
"String: %s",
"StyleManager: There is a definition missing for the '%s'.",
"%s won!",
"%s: Worker program 'buildferry' is deprecated. Use createbob=TRIBENAME_ferry instead.",
"target quantity configured for \"%s\" in ware economy, ",
"target quantity configured for \"%s\" in worker economy, ",
"target quantity configured for ware %s, ",
"target quantity configured for worker %s, ",
"Terrain '%s' contains obsolete 'tooltips' table",
"The AI needs the tribe '%s' to define 1 type of barracks building. ",
"The AI needs the tribe '%s' to define 1 type of fisher's building. ",
"The AI needs the tribe '%s' to define 1 type of hunter's building at the most. ",
"The AI needs the tribe '%s' to define 1 type of well at the most. ",
"The bakery needs %s on average to produce one loaf of bread.",
"The barracks needs %s on average to recruit one soldier.",
"The beekeeper pauses %s before going to work again.",
"The berry farmer pauses %s before going to work again.",
"The blacksmith needs %s on average to produce one tool.",
"The brewery needs %s on average to brew one mug of beer.",
"The brick kiln needs %s on average to produce three bricks.",
"the building doesn’t have the following wares: %s",
"the building has the following wares: %s",
"The carrier needs %s to get one bucket full of water.",
"The charcoal burner’s house needs %s on average to produce one coal.",
"The charcoal kiln needs %s on average to produce one coal.",
"The charcoal kiln needs %s on average to produce one lump of coal.",
"The chocolate brewery needs %s on average to brew one mug of chocolate.",
"The client %s could not be found.",
"the economy doesn’t need the ware ‘%s’",
"the economy doesn’t need the worker ‘%s’",
"the economy needs the ware ‘%s’",
"the economy needs the worker ‘%s’",
"The fisher pauses %s before going to work again.",
"The forester pauses %s before going to work again.",
"The fruit collector pauses %s before going to work again.",
"The game %s has been closed",
"The game %s is already running. Please choose a different name.",
"The game %s is now available",
"The game will end in %s.",
"The hunter-gatherer pauses %s before going to work again.",
"The hunter pauses %s before going to work again.",
"The \"indicate_workarea_overlaps\" table in %s has been deprecated and can be ",
"The initiation site needs %s on average to recruit one soldier.",
"The liana cutter rests %s before going to work again.",
"The main program for the building %s should be renamed from 'work' to ",
"The main program for the immovable %s should be renamed from 'program' ",
"Theme '%s' not found",
"Theme '%s' not found, using fallback image",
"The name of this map in your language: %s",
"The original name of this map: %s",
"The player ‘%s’ was defeated and became a spectator.",
"The registry file %s\n",
"The required add-on ‘%s’ could not be found on the server.",
"The scout pauses %s before going to work again.",
"The sewing room needs %s on average to produce one fur garment.",
"The smokery needs %s on average to smoke two fish or two meat.",
"The stated reason was: %s",
"The stonemason pauses %s before going back to work again.",
"The stonemason pauses %s before going to work again.",
"The translation into %s is complete.",
"The weaving mill needs %s on average to produce one piece of cloth.",
"The well needs %s on average to produce one bucket of water.",
"This is Widelands Version %s",
"Toggle category ‘%s’",
"Training site '%s' is lacking its 'messages' table",
"Trainingsite '%s': Keys 'min_level' and 'max_level' in table 'soldier ",
"Training wheel '%s' acquired the lock",
"transfer: %s",
"Tribe %s: Specifying `carrier`/`carrier2` instead of `carriers` is deprecated",
"Tried to add %s twice.",
"True Type library did not initialize: %s\n",
"Trying to run %s",
"   type             %7s",
"   type_            %7s",
"   <typename>       %s",
"Unable to determine truth value for \"%s\"",
"Unable to get absolute path for %s",
"Unable to load the win condition script file ‘%s’.",
"Unidentified registry caller for tribe add-on (unit: %s)",
"Unidentified registry caller for world add-on (unit: %s)",
"Unknown command line parameter: %s",
"unknown command type \"%s\"",
"unknown critter %s",
"unknown immovable %s",
"Unknown player state: %s\n",
"Unknown script direction '%s'. Using to left-to-right rendering.\n",
"Unknown user has left the game (%s)",
"Unlocking mutex %s",
"Unsolved training wheel '%s'",
"Unused key \"%s\" in LuaTable. Please report as a bug.\n",
"update_planned_workers: bad buildcost '%s'",
"upload addon %s cancelled by user",
"Uploading ‘%s’…",
"Upload Screenshot for ‘%s’",
"Usage: %s <existing-output-path>\n",
"Usage: %s <map file>\n",
"Usage: %s <mapobject_name> <animation_name> <existing-output-path>\n",
"using locale %s\n",
"Using old syntax in %s. Please use ",
"Using old syntax in %s. Please use 'mine=<resource name> radius:<number> ",
"Using old syntax in %s. Please use train=soldier:attack|defense|evade|health ",
"VIDEO DRIVER GLVND %s\n",
"VIDEO DRIVER %s\n",
"WareInstance: %s",
"WARNING: Could not open %s for reading!\n",
"WARNING: Received a %s command although we are not in CONNECTING state.",
"Widelands could not find the file \"%s\".",
"Widelands executable directory: %s\n",
"Win condition file \"%s\" does not exist",
"Win Condition: %s",
"Workers: %s",
"world does not define immovable type %s, you cannot ",
"world does not define resource type %s, you cannot ",
"world does not define terrain type %s, you cannot ",
"World:         %s\n",
"Write to %s failed",
"Wrong argument type: expected bool, found %s",
"Wrong argument type: expected char, found %s",
"Wrong argument type: expected string, found %s",
"You can also use the hotkey ‘%s’.",
"You can also use the hotkey ‘%s’ to access this window quickly.",
"Your %s can’t find a way home and will likely die."
};

static const uint kNFmtStr = formats_str.size();

