/*
 * Copyright (C) 2021 by the Widelands Development Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

#include <boost/format.hpp>
#include <vector>

static const std::vector<boost::format> formats_str = {
boost::format("ABORTING. Unable to find map object for '%s'!\n"),
boost::format("ActConstruct: immovable '%s' does not exist"),
boost::format("act: %s"),
boost::format("Adding directory: %s\n"),
boost::format("┃    Add-On ‘%s’"),
boost::format("Add-on '%s' not found"),
boost::format("Add-on %s required by host not found"),
boost::format("A file with the name ‘%s’ already exists. Overwrite?"),
boost::format("AI: Max preciousness must not be <= 0 for building: %s"),
boost::format("Alternatively, you can access it directly with the ‘%s’ key."),
boost::format("Animals: %s"),
boost::format("A reed yard can produce a sheaf of reed in about %s on average."),
boost::format("Are you sure you want to kick %s?"),
boost::format("Author: %s"),
boost::format("Autosave: Deleted %s\n"),
boost::format("Autosave: ERROR! - %s\n"),
boost::format("Autosave: saving as %s\n"),
boost::format("Back to ‘%s’"),
boost::format("Backup file ‘%s’ could not be deleted."),
boost::format("Backup file ‘%s’ will be available for some time."),
boost::format("battle: %s"),
boost::format("[BufferedConnection] Connection to %s."),
boost::format("   Building name    %s"),
boost::format("by %s"),
boost::format("call economy balance: %s"),
boost::format("   can_act_         %7s"),
boost::format("Caps: %s"),
boost::format("Category: %s"),
boost::format("Clicking button '%s'\n"),
boost::format("Clicking tab '%s'\n"),
boost::format("Client sent malformed commands: %s"),
boost::format("Client %s is cheating!"),
boost::format("Closing window '%s'\n"),
boost::format("Completed %s"),
boost::format("contact error: %s"),
boost::format("Could not create %s shader."),
boost::format("could not load \"%s\""),
boost::format("Could not read locale fontset for: %s\n"),
boost::format("Could not read locale for: %s\n"),
boost::format("Could not read locales fontset information from file: %s\n"),
boost::format("Could not read locales information from file: %s\n"),
boost::format("could not save configuration: %s\n"),
boost::format("could not save training wheels: %s\n"),
boost::format("count_all_dependencies: '%s' not installed"),
boost::format("Created constructionsite for a %s, which is not of any known building type\n"),
boost::format("Current directory: %s"),
boost::format("Current: %s …"),
boost::format("Current: %s"),
boost::format("Default template directory '%s' does not exist!"),
boost::format("Delete syncstream or replay %s\n"),
boost::format("Deleting generated ai file: %s\n"),
boost::format("Deleting old temp backup file: %s\n"),
boost::format("Deleting old temp file: %s\n"),
boost::format("Deprecated enhancement code found in building '%s'"),
boost::format("Deprecated enhancement_cost code found in building '%s'"),
boost::format("Deprecated usage in %s. Please convert playsound's 'priority' option to "),
boost::format("Description: %s"),
boost::format("Directory ‘%s’ could not be created!"),
boost::format("Done running %s."),
boost::format("Downloading ‘%s’…"),
boost::format("Do you really want to commit all changes to the add-on ‘%s’ to disk?"),
boost::format("Do you really want to delete the add-on ‘%s’?"),
boost::format("Do you really want to delete the directory ‘%s’ and all its contents?"),
boost::format("Do you really want to delete the map ‘%s’?"),
boost::format("Do you really want to discard all changes to the add-on ‘%s’?"),
boost::format("Do you really want to sink %s?"),
boost::format("Do you really want to upload the add-on ‘%s’ to the server?"),
boost::format("Economy::create_requested_worker: buildcost inconsistency '%s'"),
boost::format("Emergency save failed because: %s"),
boost::format("Empty helptext defined for '%s'"),
boost::format("Empty value of command line parameter: %s"),
boost::format("Enabled Add-Ons: %s"),
boost::format("Enhance to %s"),
boost::format("Error allocating game: %s"),
boost::format("Error in animation table: %s"),
boost::format("Error linking:\n%s"),
boost::format("Error loading script for editor help:\n%s\n"),
boost::format("Error loading script for encyclopedia:\n%s\n"),
boost::format("Error parsing datadir: %s\n"),
boost::format("Error: %s"),
boost::format("ERROR: %s"),
boost::format("Error trying to fetch Arabic character form: %s\n"),
boost::format("Error trying to fetch Arabic diacritic form: %s\n"),
boost::format("Error while creating directory ‘%s’."),
boost::format("Error writing data to file ‘%s’!"),
boost::format("Exception: %s.\n"),
boost::format("Failed to initialize SDL, no valid video driver: %s"),
boost::format("Failed to initialize sound system: %s\n"),
boost::format("Failed to load the minimap image: %s"),
boost::format("Failed to load the minimap image : %s\n"),
boost::format("Failed to save game for replay: %s"),
boost::format("Failed to write into zipfile %s"),
boost::format("Fastplace defaults: Unused key '%s'"),
boost::format("Fatal exception: %s\n"),
boost::format("Filename may not contain ‘%s’"),
boost::format("File name '%s' is not allowed in scenario tribes – expecting "),
boost::format("File ‘%s’ could not be removed!"),
boost::format("File ‘%s’ could not be restored!"),
boost::format("File ‘%s’ was restored from backup."),
boost::format("Found deprecated 'pictures' parameter in animation with file\n   %s\n"),
boost::format("Game not started: Game data error: %s\n"),
boost::format("Gametime: %s"),
boost::format("Graphics: OpenGL: ShadingLanguage: \"%s\"\n"),
boost::format("Graphics: OpenGL: Version \"%s\"\n"),
boost::format("   has_priority_    %7s"),
boost::format("Help: %s"),
boost::format("Helptexts script for %s is obsolete - please move strings to "),
boost::format("Hint: %s"),
boost::format("Host sent player %s to the lobby!"),
boost::format("ID:            %s\n"),
boost::format("If yes, type: /ack_kick %s"),
boost::format("If you wish to help us translate, please visit %s"),
boost::format("Ignoring malformed add-ons config substring '%s'\n"),
boost::format("Ignoring malformed fastplace config string: %s"),
boost::format("Image not found: %s"),
boost::format("ImmovableActionData::load: type %s not known"),
boost::format("Immovable: %s"),
boost::format("immovable type: %s"),
boost::format("Incompatible: %s"),
boost::format("incorporate: %s"),
boost::format("install addon %s cancelled by user"),
boost::format("install translations for %s cancelled by user"),
boost::format("InternetGaming: Client announced the start of the game %s."),
boost::format("InternetGaming: Client opened a game with the name %s."),
boost::format("InternetGaming: Client tries to join a game with the name %s"),
boost::format("InternetGaming: Error: %s\n"),
boost::format("InternetGaming: logout(%s)"),
boost::format("InternetGaming: Password check successful at UTC %s"),
boost::format("InternetGaming: Received %s cmd although client is not in CONNECTING state.\n"),
boost::format("InternetGaming: Strange ERROR in connecting state: %s\n"),
boost::format("Invalid add-on category '%s'"),
boost::format("Invalid chat message type \"%s\"."),
boost::format("Invalid map file '%s'"),
boost::format("invalid MapGenBobCategory %s"),
boost::format("Invalid path to file in campaigns.lua of tutorials.lua: %s"),
boost::format("Invalid richtext: %s"),
boost::format("Invalid soldier preference '%s'"),
boost::format("invalid syntax: %s"),
boost::format("invalid tribe ‘%s’"),
boost::format("Invalid ware priority '%s'"),
boost::format("Is: %s"),
boost::format("key %s outside section"),
boost::format("Kicked by the host: %s"),
boost::format("[LAN] Will broadcast to %s."),
boost::format("LayeredFileSystem: No writable filesystem for dir: %s!"),
boost::format("LayeredFileSystem: No writable filesystem for %s!"),
boost::format("LayeredFileSystem: unable to create sub filesystem for new directory: %s"),
boost::format("Loading Battle: %s"),
boost::format("loading bob: %s"),
boost::format("loading carrier: %s"),
boost::format("loading critter: %s"),
boost::format("loading ferry fleet: %s"),
boost::format("loading ferry: %s"),
boost::format("Loading map “%s”…"),
boost::format("loading player immovable: %s"),
boost::format("loading portdock: %s"),
boost::format("┏━ Loading %s"),
boost::format("loading ship fleet: %s"),
boost::format("loading shipping schedule: %s"),
boost::format("loading ship: %s"),
boost::format("loading soldier: %s"),
boost::format("loading worker: %s"),
boost::format("Logged in as %s"),
boost::format("Logged in as %s (admin)"),
boost::format("Manually running training wheel '%s'"),
boost::format("MapAllowedBuildingTypesPacket - tribe %s does not define "),
boost::format("Map::get_correct_loader: File error: %s\n"),
boost::format("Map::get_correct_loader: Unknown error: %s\n"),
boost::format("map object: %s"),
boost::format("Map: %s"),
boost::format("Mapselect: Skip %s due to unknown exception\n"),
boost::format("Map '%s' is both balanced and unbalanced - please fix the 'elemental' "),
boost::format("missing ']' after \"%s\""),
boost::format("       Name         %s"),
boost::format("Name: %s"),
boost::format("\n\n=========================\nWriting tribe: %s\n=========================\n"),
boost::format("No backgrounds found for theme '%s', using fallback image"),
boost::format("No helptext defined for '%s'"),
boost::format("No locale translations found in %s\n"),
boost::format("Not enough space to draw spinbox \"%s\".\n"),
boost::format("Not loading add-on '%s' (not found)\n"),
boost::format("Not loading add-on '%s' (wrong file name extension)\n"),
boost::format("Old-style syntax found for 'construct' program in %s, use "),
boost::format("Opening dropdown '%s'\n"),
boost::format("plan_workers: bad buildcost '%s'"),
boost::format("player-requested file deletion failed: %s"),
boost::format("Players: %s"),
boost::format("preload_addon (%s): category is None"),
boost::format("preload_addon (%s): version string is empty"),
boost::format("Pressing button '%s'\n"),
boost::format("Press ‘%s’ to quickly toggle the display of your stock inventory."),
boost::format("Produced %s"),
boost::format("productionsite has failed/skipped program \"%s\", which "),
boost::format("productionsite has unknown program \"%s\", replacing it with "),
boost::format("Realpath: %s\n"),
boost::format("Received an unknown command from the metaserver: %s"),
boost::format("Received command number %s, which is not allowed in this state."),
boost::format("Recruited %s"),
boost::format("Registry file %s does not define any units"),
boost::format("Replace player with %s"),
boost::format("REPLAY: Caught exception %s\n"),
boost::format("request: %s"),
boost::format("requirements: %s"),
boost::format("Requires a Widelands version of at least %s."),
boost::format("Requires a Widelands version of at most %s."),
boost::format("Running postload script for add-on %s"),
boost::format("Running preload script for add-on %s"),
boost::format("Running training wheel '%s'"),
boost::format("Running training wheels. Current active is %s"),
boost::format("  -> %s"),
boost::format(" %s"),
boost::format(" -> %s"),
boost::format("%s"),
boost::format("%s("),
boost::format("%s:"),
boost::format("(%s)"),
boost::format("· %s"),
boost::format("“%s”"),
boost::format("%s and"),
boost::format("%s anywhere in the filename"),
boost::format("%s apparently not a valid replay file"),
boost::format("%s are missing"),
boost::format("%s at the start of the filename"),
boost::format("Saved: %s"),
boost::format("Save handler returned error: %s"),
boost::format("Save screenshot to %s\n"),
boost::format("%s can not be combined with other actions"),
boost::format("Scenario not started: Game data error: %s\n"),
boost::format("Script requests save to: %s\n"),
boost::format("Script %s not found."),
boost::format("%s: Deprecated 'bob' in 'transform' program, use 'bob:<name>' instead.\n"),
boost::format("%s: Deprecated chance in 'remove' program, use 'chance:<percent>' instead.\n"),
boost::format("%s: Deprecated chance in 'transform' program, use 'chance:<percent>' "),
boost::format("SDL_GL_LoadLibrary failed: %s"),
boost::format("selected language: %s\n"),
boost::format("Selecting current item in dropdown '%s'\n"),
boost::format("Set configuration file: %s"),
boost::format("Set home directory: %s\n"),
boost::format(" - Set LANGUAGE, LANG and LC_ALL to '%s'\n"),
boost::format("set_login (''): server error (%s)"),
boost::format(" - Set system locale to 'en_US.utf8' to make '%s' accessible to libintl\n"),
boost::format("set_template_dir: template directory '%s' does not exist, using default template"),
boost::format("%s has joined the game"),
boost::format("%s has no animation assigned for its representative image, or it's not a known "),
boost::format("%s has not been saved"),
boost::format("%s has won the game. Congratulations!"),
boost::format("Ships: %s"),
boost::format("Shortcut '%s' does not exist"),
boost::format("   show_only_       %7s"),
boost::format("%s is a replay from a version that is known to have desync "),
boost::format("%s is missing"),
boost::format("%s is not a directory. Please fix this.\n"),
boost::format("Size: %s"),
boost::format("%s joined the lobby"),
boost::format("Skipped CmdSetInputMaxFill command: %s"),
boost::format("Skipped running training wheel '%s'"),
boost::format("Skipping training wheel '%s'"),
boost::format("%s left the lobby"),
boost::format("%s lost control of the hill."),
boost::format("%s (missing)"),
boost::format(" [%s]\n"),
boost::format("%s\n"),
boost::format("*** %s\n"),
boost::format("Solved training wheel '%s'"),
boost::format("Something went wrong: %s"),
boost::format("Songset: Loaded song \"%s\"\n"),
boost::format("Songset: Loading song \"%s\" failed!\n"),
boost::format("Songset: %s\n"),
boost::format("%s or better"),
boost::format("SoundHandler: Audio error %s\n"),
boost::format("SoundHandler: Mix_PlayChannel failed: %s\n"),
boost::format("SoundHandler: SDL_AUDIODRIVER %s\n"),
boost::format("SoundHandler: songset \"%s\" does not exist!\n"),
boost::format("%s owns more than half of the map’s area."),
boost::format("Starting to lock mutex %s (run_while_waiting) ..."),
boost::format("Status for %s"),
boost::format("%s: The 'collects_ware_from_map' key in 'ai_hints' is no longer used"),
boost::format("%s: The 'mines' key in 'ai_hints' is no longer used"),
boost::format("%s: The 'supports_production_of' key in 'ai_hints' is no longer used"),
boost::format("   Stopped          %7s"),
boost::format("String: %s"),
boost::format("StyleManager: There is a definition missing for the '%s'."),
boost::format("%s won!"),
boost::format("%s: Worker program 'buildferry' is deprecated. Use createbob=TRIBENAME_ferry instead."),
boost::format("target quantity configured for \"%s\" in ware economy, "),
boost::format("target quantity configured for \"%s\" in worker economy, "),
boost::format("target quantity configured for ware %s, "),
boost::format("target quantity configured for worker %s, "),
boost::format("Terrain '%s' contains obsolete 'tooltips' table"),
boost::format("The AI needs the tribe '%s' to define 1 type of barracks building. "),
boost::format("The AI needs the tribe '%s' to define 1 type of fisher's building. "),
boost::format("The AI needs the tribe '%s' to define 1 type of hunter's building at the most. "),
boost::format("The AI needs the tribe '%s' to define 1 type of well at the most. "),
boost::format("The bakery needs %s on average to produce one loaf of bread."),
boost::format("The barracks needs %s on average to recruit one soldier."),
boost::format("The beekeeper pauses %s before going to work again."),
boost::format("The berry farmer pauses %s before going to work again."),
boost::format("The blacksmith needs %s on average to produce one tool."),
boost::format("The brewery needs %s on average to brew one mug of beer."),
boost::format("The brick kiln needs %s on average to produce three bricks."),
boost::format("the building doesn’t have the following wares: %s"),
boost::format("the building has the following wares: %s"),
boost::format("The carrier needs %s to get one bucket full of water."),
boost::format("The charcoal burner’s house needs %s on average to produce one coal."),
boost::format("The charcoal kiln needs %s on average to produce one coal."),
boost::format("The charcoal kiln needs %s on average to produce one lump of coal."),
boost::format("The chocolate brewery needs %s on average to brew one mug of chocolate."),
boost::format("The client %s could not be found."),
boost::format("the economy doesn’t need the ware ‘%s’"),
boost::format("the economy doesn’t need the worker ‘%s’"),
boost::format("the economy needs the ware ‘%s’"),
boost::format("the economy needs the worker ‘%s’"),
boost::format("The fisher pauses %s before going to work again."),
boost::format("The forester pauses %s before going to work again."),
boost::format("The fruit collector pauses %s before going to work again."),
boost::format("The game %s has been closed"),
boost::format("The game %s is already running. Please choose a different name."),
boost::format("The game %s is now available"),
boost::format("The game will end in %s."),
boost::format("The hunter-gatherer pauses %s before going to work again."),
boost::format("The hunter pauses %s before going to work again."),
boost::format("The \"indicate_workarea_overlaps\" table in %s has been deprecated and can be "),
boost::format("The initiation site needs %s on average to recruit one soldier."),
boost::format("The liana cutter rests %s before going to work again."),
boost::format("The main program for the building %s should be renamed from 'work' to "),
boost::format("The main program for the immovable %s should be renamed from 'program' "),
boost::format("Theme '%s' not found"),
boost::format("Theme '%s' not found, using fallback image"),
boost::format("The name of this map in your language: %s"),
boost::format("The original name of this map: %s"),
boost::format("The player ‘%s’ was defeated and became a spectator."),
boost::format("The registry file %s\n"),
boost::format("The required add-on ‘%s’ could not be found on the server."),
boost::format("The scout pauses %s before going to work again."),
boost::format("The sewing room needs %s on average to produce one fur garment."),
boost::format("The smokery needs %s on average to smoke two fish or two meat."),
boost::format("The stated reason was: %s"),
boost::format("The stonemason pauses %s before going back to work again."),
boost::format("The stonemason pauses %s before going to work again."),
boost::format("The translation into %s is complete."),
boost::format("The weaving mill needs %s on average to produce one piece of cloth."),
boost::format("The well needs %s on average to produce one bucket of water."),
boost::format("This is Widelands Version %s"),
boost::format("Toggle category ‘%s’"),
boost::format("Training site '%s' is lacking its 'messages' table"),
boost::format("Trainingsite '%s': Keys 'min_level' and 'max_level' in table 'soldier "),
boost::format("Training wheel '%s' acquired the lock"),
boost::format("transfer: %s"),
boost::format("Tribe %s: Specifying `carrier`/`carrier2` instead of `carriers` is deprecated"),
boost::format("Tried to add %s twice."),
boost::format("True Type library did not initialize: %s\n"),
boost::format("Trying to run %s"),
boost::format("   type             %7s"),
boost::format("   type_            %7s"),
boost::format("   <typename>       %s"),
boost::format("Unable to determine truth value for \"%s\""),
boost::format("Unable to get absolute path for %s"),
boost::format("Unable to load the win condition script file ‘%s’."),
boost::format("Unidentified registry caller for tribe add-on (unit: %s)"),
boost::format("Unidentified registry caller for world add-on (unit: %s)"),
boost::format("Unknown command line parameter: %s"),
boost::format("unknown command type \"%s\""),
boost::format("unknown critter %s"),
boost::format("unknown immovable %s"),
boost::format("Unknown player state: %s\n"),
boost::format("Unknown script direction '%s'. Using to left-to-right rendering.\n"),
boost::format("Unknown user has left the game (%s)"),
boost::format("Unlocking mutex %s"),
boost::format("Unsolved training wheel '%s'"),
boost::format("Unused key \"%s\" in LuaTable. Please report as a bug.\n"),
boost::format("update_planned_workers: bad buildcost '%s'"),
boost::format("upload addon %s cancelled by user"),
boost::format("Uploading ‘%s’…"),
boost::format("Upload Screenshot for ‘%s’"),
boost::format("Usage: %s <existing-output-path>\n"),
boost::format("Usage: %s <map file>\n"),
boost::format("Usage: %s <mapobject_name> <animation_name> <existing-output-path>\n"),
boost::format("using locale %s\n"),
boost::format("Using old syntax in %s. Please use "),
boost::format("Using old syntax in %s. Please use 'mine=<resource name> radius:<number> "),
boost::format("Using old syntax in %s. Please use train=soldier:attack|defense|evade|health "),
boost::format("VIDEO DRIVER GLVND %s\n"),
boost::format("VIDEO DRIVER %s\n"),
boost::format("WareInstance: %s"),
boost::format("WARNING: Could not open %s for reading!\n"),
boost::format("WARNING: Received a %s command although we are not in CONNECTING state."),
boost::format("Widelands could not find the file \"%s\"."),
boost::format("Widelands executable directory: %s\n"),
boost::format("Win condition file \"%s\" does not exist"),
boost::format("Win Condition: %s"),
boost::format("Workers: %s"),
boost::format("world does not define immovable type %s, you cannot "),
boost::format("world does not define resource type %s, you cannot "),
boost::format("world does not define terrain type %s, you cannot "),
boost::format("World:         %s\n"),
boost::format("Write to %s failed"),
boost::format("Wrong argument type: expected bool, found %s"),
boost::format("Wrong argument type: expected char, found %s"),
boost::format("Wrong argument type: expected string, found %s"),
boost::format("You can also use the hotkey ‘%s’."),
boost::format("You can also use the hotkey ‘%s’ to access this window quickly."),
boost::format("Your %s can’t find a way home and will likely die.")
};

static const uint kNFmtStr = formats_str.size();

