/*
 * Copyright (C) 2021 by the Widelands Development Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

#ifndef WL_BASE_FMT_BENCH_CONST_STR
#define WL_BASE_FMT_BENCH_CONST_STR

#include <string>
#include <vector>

static const std::vector<std::string> const_strings = {
"Abacaxis",
"Abaco",
"Acari",
"Acre",
"Açuã",
"Acurauá",
"Adriatic Sea",
"Advanced Shield",
"Advanced Spear",
"Agate",
"Agilaz",
"Aiari",
"Alalaú",
"Alexandria",
"Alexandrite",
"A Lot of Coal",
"A Lot of Crystals",
"A Lot of Gold",
"A Lot of Granite",
"A Lot of Iron",
"A Lot of Marble",
"Alt-Nordstrand",
"Amalea",
"Amanã",
"Amapá",
"Amazonas",
"Amazons (experimental)",
"Amber",
"Amethyst",
"Amolius",
"Amrum",
"Anchicayá",
"Andirá",
"Anguilla",
"Antigua",
"Antimary",
"Apollo",
"Apoquitaua",
"Apuaú",
"Aqua Farm",
"Aquamarine",
"Araçá",
"Arara",
"Ararirá",
"Arauã",
"Arena",
"Aripuanã",
"Armor",
"Armorsmith",
"Armor Smithy",
"Arrojo",
"Ashes",
"Aslaug",
"Atiparaná",
"Atlanteans",
"Atlantean’s Stronghold",
"Atlantis",
"Atucatiquini",
"Augustus",
"Autaz-mirim",
"Ax",
"Ax Workshop",
"Azurea Sea",
"Badajós",
"Bahama",
"Baker",
"Bakery",
"baking bread",
"baking honey bread",
"baking pitta bread",
"Baldr",
"Balsa",
"Balsa Tree",
"Balsa Tree (Mature)",
"Balsa Tree (Old)",
"Balsa Tree (Pole)",
"Balsa Tree (Sapling)",
"Baltic Sea",
"Bararati",
"Barbados",
"Barbarians",
"Barbuda",
"Barley",
"Barley Field (harvested)",
"Barley Field (medium)",
"Barley Field (ripe)",
"Barley Field (small)",
"Barley Field (tiny)",
"Barracks",
"Barrier",
"Basket",
"Battle Arena",
"Battle Ax",
"Bear",
"Be careful",
"Beekeeper",
"Beekeeper’s House",
"Beer",
"Bellona",
"Ben Hur",
"Beowulf",
"Berry Farm",
"Berry Farmer",
"Beryl",
"Biá",
"Big Inn",
"Black Currant (medium)",
"Black Currant (ripe)",
"Black Currant (small)",
"Black Currant (tiny)",
"Blackroot",
"Blackroot Farm",
"Blackroot Farmer",
"Blackroot Field (harvested)",
"Blackroot Field (medium)",
"Blackroot Field (ripe)",
"Blackroot Field (small)",
"Blackroot Field (tiny)",
"Blackroot Flour",
"Blacksmith",
"Blacksmithy",
"Blackwood",
"Blanquilla",
"Blockhouse",
"Blueberry Bush (medium)",
"Blueberry Bush (ripe)",
"Blueberry Bush (small)",
"Blueberry Bush (tiny)",
"Boldreth",
"Bounty",
"Bread",
"Bread Paddle",
"breeding fish",
"breeding horses",
"breeding sheep",
"breeding tapir",
"Brewer",
"Brewery",
"brewing beer",
"brewing chocolate",
"brewing mead",
"brewing strong beer",
"Brick",
"Brick Kiln",
"Brickmaker",
"Broad Ax",
"Broadsword",
"Bronze Ax",
"Brutus",
"Buckets",
"Builder",
"Buildings",
"burning bricks",
"Burning Charcoal Stack",
"Caesar",
"Caicos",
"Caligula",
"Camaiú",
"Camanaú",
"Camilla",
"Canumã",
"Capucapu",
"Carabinani",
"Carpenter",
"Carrara",
"Carrier",
"Cassava Farmer",
"Cassava Field (harvested)",
"Cassava Field (medium)",
"Cassava Field (ripe)",
"Cassava Field (small)",
"Cassava Field (tiny)",
"Cassava Plantation",
"Cassava Root",
"Cassava Root Cooker",
"Cassiterite",
"Castle",
"Cat’s Eye",
"Cattle Breeder",
"Cattle Farm",
"Cauaburi",
"Caurés",
"Chain Armor",
"Charcoal Burner",
"Charcoal Burner’s House",
"Charcoal Kiln",
"Chat’Karuth",
"Chief Miner",
"Chisel",
"Chocolate",
"Chocolate Brewery",
"Cicero",
"Ciriquiri",
"Citadel",
"Citrine",
"Claudius",
"Clay",
"Clay Digger",
"Clay Pit",
"Cloth",
"Coal",
"Coal Mine",
"Coari",
"Cocoa Beans",
"Cocoa Farm",
"Cocoa Farmer",
"Cocoa Tree (mature)",
"Cocoa Tree (old)",
"Cocoa Tree (pole)",
"Cocoa Tree (sapling)",
"Colionder",
"collecting coal",
"Colosseum",
"constructing a ship",
"Construction Site",
"Controls",
"Cook",
"Copatana",
"Corn",
"Cornfield (harvested)",
"Cornfield (medium)",
"Cornfield (ripe)",
"Cornfield (small)",
"Cornfield (tiny)",
"Cornmeal",
"Coti",
"Crystal Mine",
"Cubate",
"Cuiari",
"Cuieiras",
"Cuini",
"Cuniuá",
"Curicuriari",
"Curiuaú",
"Curuçá",
"Curuduri",
"Curuquetê",
"cutting granite",
"cutting lianas",
"Daraá",
"Dead Tree",
"Deep Coal Mine",
"Deeper Coal Mine",
"Deeper Gold Mine",
"Deeper Iron Mine",
"Deep Gold Mine",
"Deep Iron Mine",
"Deep Marble Mine",
"Deep Rock Mine",
"Dellingr",
"Demini",
"Desert Hackberry (medium)",
"Desert Hackberry (ripe)",
"Desert Hackberry (small)",
"Desert Hackberry (tiny)",
"Destroyed building",
"Diamond",
"Diana",
"Discovery",
"Dismantle Site",
"Dominica",
"Domitianus",
"Donkey",
"Donkey Breeder",
"Donkey Farm",
"Dos Marmelos",
"Double-edged Sword",
"Double Trident",
"Dressmaker",
"Dressmakery",
"Drinking Hall",
"Dry Pond",
"Dungeon",
"Efficiency",
"Eiderstedt",
"Eiru",
"Eleuthera",
"Emerald",
"Empire",
"Empire Glory",
"Endimari",
"enhancing the fertility of land",
"Envira",
"Farm",
"Farmer",
"Faustulus",
"Felling Ax",
"felling trees",
"Ferry",
"Ferry Yard",
"Fire Tongs",
"Fish",
"Fish Breeder",
"Fish Breeder’s House",
"Fisher",
"Fisher’s House",
"Fisher’s Hut",
"fishing",
"Fishing Net",
"Fishing Rod",
"Flour",
"Föhr",
"Food Preserver",
"Forester",
"Forester’s House",
"forging a battle ax",
"forging a broad ax",
"forging a broadsword",
"forging a bronze ax",
"forging a double-edged sword",
"forging a double trident",
"forging a felling ax",
"forging a golden helmet",
"forging a heavy double trident",
"forging a heavy spear",
"forging a helmet",
"forging a light trident",
"forging a long sword",
"forging a long trident",
"forging a mask",
"forging an advanced shield",
"forging an advanced spear",
"forging an ax",
"forging a pick",
"forging a sharp ax",
"forging a short sword",
"forging a spear",
"forging a steel shield",
"forging a steel trident",
"forging a suit of armor",
"forging a suit of chain armor",
"forging a suit of gilded armor",
"forging a warhelm",
"forging a warrior’s ax",
"forging a war spear",
"forging a wooden spear",
"Fortification",
"Fortified Village",
"Fortress",
"Frisians",
"Fruit",
"Fruit Collector",
"Fruit Collector’s House",
"Fulla",
"Fur",
"Fur Garment",
"Furnace",
"Galba",
"Gallus",
"Gamekeeper",
"Gamekeeper’s Hut",
"Gardener",
"Gardening Center",
"gathering",
"gathering berries",
"gathering fish",
"gathering meat",
"General",
"Geologist",
"Gersemi",
"Gilded Armor",
"Gold",
"Gold Digger",
"Gold Digger Dwelling",
"Gold Dust",
"Golden Fur Garment",
"Golden Helmet",
"Golden Tabard",
"Gold Mine",
"Gold Ore",
"Gold Smelter",
"Gold Spinning Mill",
"Gold Thread",
"Granite",
"Granite Mine",
"Grape",
"Grapevine (medium)",
"Grapevine (ripe)",
"Grapevine (small)",
"Grapevine (tiny)",
"Gregório",
"Grenada",
"grinding blackroot",
"grinding corn",
"grinding wheat",
"Gröde",
"Grout",
"Guadeloupe",
"Guáitara",
"Guardhall",
"Guardhouse",
"Guaribe",
"Habel",
"Hagbard",
"Hamburger Hallig",
"Hammer",
"Hardened Spear",
"hardening wood",
"harvesting balsa",
"harvesting barley",
"harvesting blackroot",
"harvesting cassava",
"harvesting cocoa",
"harvesting corn",
"harvesting grapes",
"harvesting ironwood",
"harvesting reed",
"harvesting rubber",
"harvesting wheat",
"Headquarters",
"Headquarters Shipwreck",
"Heavy Double Trident",
"Heavy Spear",
"Heidrek",
"Heimdallr",
"Helgoland",
"Helmet",
"Helmsmith",
"Helm Smithy",
"Hero Boots",
"Hever",
"High Tower",
"High Wooden Tower",
"Hnoss",
"Honey",
"Honey Bread",
"Honey Bread Bakery",
"Hooge",
"Hook Pole",
"Horse",
"Horse Breeder",
"Horse Farm",
"Hrothgar",
"Hunter",
"Hunter-Gatherer",
"Hunter-Gatherer’s Hut",
"Hunter’s House",
"Hunter’s Hut",
"hunting",
"Hunting Bow",
"Hunting Spear",
"Iá",
"Iaco",
"Ianus",
"Içá",
"Içana",
"Immovables",
"Inagua",
"Inauini",
"Ingeld",
"Initiation Site",
"Inn",
"Innkeeper",
"Introduction",
"Ipixuna",
"Iron",
"Iron Mine",
"Iron Ore",
"Ironwood",
"Ironwood Tree",
"Ironwood Tree (Mature)",
"Ironwood Tree (Old)",
"Ironwood Tree (Pole)",
"Ironwood Tree (Sapling)",
"Iscuandé",
"Itanhauá",
"Itaparaná",
"Itaquai",
"Itucumã",
"Ituí",
"Ituxi",
"Iulius Caesar",
"Iuno",
"Iupiter",
"Jacaré",
"Jamicia",
"Jandiatuba",
"Japsand",
"Japurá",
"Jaquirana",
"Jari",
"Jatapu",
"Jatuarana",
"Jaú",
"Jauaperi",
"Javary",
"Juami",
"Jufari",
"Juma",
"Jundlina",
"Jungle Master",
"Jungle Preserver",
"Jungle Preserver’s Hut",
"Juniper (medium)",
"Juniper (ripe)",
"Juniper (small)",
"Juniper (tiny)",
"Juruá",
"Juruena",
"Jurupari",
"Jutai",
"Jutaizinho",
"Juventud",
"Karl Hundason",
"Khantrukh",
"King Ajanthul",
"King Askandor",
"Kitchen Tools",
"Kitts",
"Kormoransand",
"Labyrinth",
"Landlady",
"Langeneß",
"Large Armor Smithy",
"Latium",
"Latonia",
"Leonardo",
"Liana",
"Liana Cutter",
"Liana Cutter’s Hut",
"Liberdade",
"Light Trident",
"Light Wooden Armor",
"Liguria",
"Lime-Burner",
"Lime Kiln",
"Loftomor",
"Log",
"Long Sword",
"Long Trident",
"Lumberjack",
"Lumberjack’s House",
"Lumberjack’s Hut",
"Luna",
"Lutius",
"Lynx",
"Machete",
"Madeira",
"Madeirinha",
"Maiá",
"Maici",
"Main Coal Vein Exhausted",
"Main Crystal Vein Exhausted",
"Main Gold Vein Exhausted",
"Main Granite Vein Exhausted",
"Main Iron Vein Exhausted",
"Main Marble Vein Exhausted",
"making a basket",
"making a bread paddle",
"making a charcoal stack",
"making a chisel",
"making a felling ax",
"making a fishing net",
"making a fishing rod",
"making a hammer",
"making a hardened spear",
"making a hook pole",
"making a hunting bow",
"making a hunting spear",
"making a light wooden armor",
"making a machete",
"making a padded protector",
"making a padded vest",
"making a pair of buckets",
"making a pick",
"making a rope",
"making a saw",
"making a scythe",
"making a shovel",
"making a stone bowl",
"making a stone-tipped spear",
"making a wooden helmet",
"making a wooden spear",
"making clay",
"making fire tongs",
"making hero boots",
"making kitchen tools",
"making milking tongs",
"making needles",
"making sturdy boots",
"making swift boots",
"making wine",
"Malachite",
"Mamiá",
"Mamoriá",
"Mamuru",
"Manacapuru",
"Mani",
"Manicoré",
"Manicorezinho",
"Mapari",
"Mapiá Grande",
"Maracanã",
"Marari",
"Marauiá",
"Marble",
"Marble Column",
"Marble Mine",
"Marié",
"Mariepauá",
"Marimari",
"Mars",
"Martinique",
"Mask",
"Master Baker",
"Master Blacksmith",
"Master Brewer",
"Master Miner",
"Master Seamstress",
"Master Woodcutter",
"Mataurá",
"Matupiri",
"Maués Açu",
"Mead",
"Mead Brewery",
"Meal",
"Meat",
"Metal Workshop",
"Micro Brewery",
"Milking Tongs",
"Mill",
"Miller",
"Miner",
"Mineruázinho",
"Minerva",
"mining coal",
"mining diamonds",
"mining gold",
"mining granite",
"mining iron",
"mining marble",
"mining quartz",
"Mixed Scrap Metal",
"mixing grout",
"Montserrat",
"Moonstone",
"Muaco",
"Mucum",
"Mutum",
"Mystic Quartz",
"Nassau",
"Needles",
"Neptune",
"Nero",
"Nerva",
"Nevis",
"New World",
"Nhamundá",
"No Bushes",
"No Coal",
"No Crystals",
"No Fields",
"No Fish",
"No Flowers",
"No Game",
"No Game, No Fish",
"No Gold",
"No Granite",
"No Ground",
"No Iron",
"No Level Ground",
"No Marble",
"No Ponds",
"Norderaue",
"Norderoog",
"Norderoogsand",
"Nordstrand",
"Nordstrandischmoor",
"No Resources",
"No Rocks",
"No soldier found for this training level!",
"No soldier to train!",
"No Trees",
"No Tree to Cut Lianas",
"No Water",
"Observation Tower",
"Obsidian",
"Octavianus",
"Odin",
"Oland",
"Old Fur Garment",
"Onyx",
"Opol",
"Orchila",
"Orinoco",
"Ostur",
"Otho",
"Out of Berries",
"Out of Clay Ponds",
"Out of Fields",
"Out of Fish",
"Out of Fish Ponds",
"Out of Flowers",
"Out of Game",
"Out of Game and Fish",
"Out of Rocks",
"Out of Trees",
"Out of Water",
"Outpost",
"Ox",
"Paciá",
"Padauari",
"Padded Protector",
"Padded Vest",
"Papagaio",
"Papuri",
"Paraconi",
"Parauari",
"Pardo",
"Pati",
"Patrol Post",
"Pauini",
"Pearl",
"Pellworm",
"Pick",
"Pig Breeder",
"Piggery",
"Pinhuã",
"Piorini",
"Piratucu",
"Pitinga",
"Pitta Bread",
"Planks",
"planting balsa tree",
"planting barley",
"planting blackroot",
"planting bushes",
"planting cassava",
"planting cocoa",
"planting corn",
"planting grapevines",
"planting ironwood tree",
"planting reed",
"planting rubber tree",
"planting trees",
"planting wheat",
"Pluto",
"Pond With Charcoal",
"Pond With Fish",
"Pond With Fish Spawn",
"Poor Hamlet",
"Port",
"Portus Bellus",
"preparing a meal",
"preparing a ration",
"preparing a snack",
"preparing only one ration",
"preparing rations",
"Preto",
"Preto da Eva",
"Prêto do Igapó-Açu",
"producing charcoal",
"producing coal",
"producing fur",
"Puduari",
"Pureté",
"Puruê",
"Purus",
"Putumayo",
"Quarry",
"quarrying granite",
"quarrying marble",
"Quartz",
"Quirinus",
"Quixito",
"raising pigs",
"Ranger",
"Ranger’s Hut",
"Rare Tree Cutter’s Hut",
"Rare Tree Plantation",
"Raspberry Bush (medium)",
"Raspberry Bush (ripe)",
"Raspberry Bush (small)",
"Raspberry Bush (tiny)",
"Ration",
"rearing cattle",
"rearing donkeys",
"rearing reindeer",
"Recruit",
"recruiting soldier",
"Recycling Center",
"recycling fur",
"recycling iron",
"recycling iron and gold",
"Red Currant (medium)",
"Red Currant (ripe)",
"Red Currant (small)",
"Red Currant (tiny)",
"Red Fox",
"Reed",
"Reed Farm",
"Reed Farmer",
"Reed Field (medium)",
"Reed Field (ripe)",
"Reed Field (small)",
"Reed Field (tiny)",
"Reed Yard",
"Reindeer",
"Reindeer Breeder",
"Reindeer Farm",
"releasing game",
"Remus",
"Rio Negro",
"Riozinho",
"Rock Mine",
"Romulus",
"Rope",
"Rope Weaver Booth",
"Rubber",
"Rubber Tree",
"Rubber Tree (Mature)",
"Rubber Tree (Old)",
"Rubber Tree (Pole)",
"Rubber Tree (Sapling)",
"Saledus",
"Sapphire",
"Satul",
"Saturn",
"Saw",
"sawing logs",
"Sawmill",
"Sawyer",
"Saxnot",
"Scout",
"scouting",
"Scout’s House",
"Scout’s Hut",
"Scrap Iron",
"sculpting a marble column",
"Scythe",
"Sea Buckthorn (medium)",
"Sea Buckthorn (ripe)",
"Sea Buckthorn (small)",
"Sea Buckthorn (tiny)",
"Seamstress",
"Sentinel",
"Sentry",
"Sepatini",
"Sepoti",
"Seruini",
"sewing a tunic",
"sewing a warrior’s coat",
"sewing fur garment",
"sewing golden fur garment",
"Sewing Room",
"sewing studded fur garment",
"Sharp Ax",
"Sheep Farm",
"Shepherd",
"Ship",
"Ship Under Construction",
"Shipwright",
"Shipyard",
"Short Sword",
"Shovel",
"Sidolus",
"Siena",
"Sigmund",
"Sigurd",
"sleeping",
"Small Armor Smithy",
"Small Tower",
"Smelter",
"smelting gold",
"smelting iron",
"Smelting Works",
"Smoked Fish",
"Smoked Meat",
"Smoker",
"Smokery",
"smoking fish",
"smoking meat",
"Snack",
"Snotra",
"Soldier",
"Some Coal",
"Some Crystals",
"Some Gold",
"Some Granite",
"Some Iron",
"Some Marble",
"Sparta",
"Spear",
"Sphalerite",
"Spider",
"Spider Breeder",
"Spidercloth",
"Spider Farm",
"Spider Silk",
"Spinel",
"spinning gold",
"Start the game with a fortified military installation",
"Start the game with a peaceful village",
"Start the game with seven ships full of wares on the ocean",
"Start the game with your headquarters only",
"Steel Shield",
"Steel Trident",
"Stink Shepherd’s Tree (medium)",
"Stink Shepherd’s Tree (ripe)",
"Stink Shepherd’s Tree (small)",
"Stink Shepherd’s Tree (tiny)",
"Stockpile",
"Stone Bowl",
"Stone Carver",
"Stonecutter",
"Stonecutter’s Hut",
"Stonemason",
"Stonemason’s House",
"Stone Mine",
"Stone-tipped Spear",
"Stone Workshop",
"Strand",
"Strawberries (medium)",
"Strawberries (ripe)",
"Strawberries (small)",
"Strawberries (tiny)",
"Strong Beer",
"Struggling Outpost",
"Studded Fur Garment",
"Sturdy Boots",
"Sucunduri",
"Süderaue",
"Süderoog",
"Süderoogsand",
"Südfall",
"Sunstone",
"Swift Boots",
"Sylt",
"Tabard",
"tailoring a golden tabard",
"tailoring a tabard",
"Tailor’s Shop",
"Tapajós",
"Tapauá",
"Tapir",
"Tapir Breeder",
"Tapir Farm",
"Tarauacá",
"Tarumã Açu",
"Tarumã Mirim",
"Tavern",
"Tea",
"Tefé",
"The carrier working at this well can’t find any water in his well.",
"The enemy defeated your soldiers at the barrier.",
"The enemy defeated your soldiers at the blockhouse.",
"The enemy defeated your soldiers at the castle.",
"The enemy defeated your soldiers at the citadel.",
"The enemy defeated your soldiers at the fortification.",
"The enemy defeated your soldiers at the fortress.",
"The enemy defeated your soldiers at the guardhall.",
"The enemy defeated your soldiers at the guardhouse.",
"The enemy defeated your soldiers at the high tower.",
"The enemy defeated your soldiers at the high wooden tower.",
"The enemy defeated your soldiers at the observation tower.",
"The enemy defeated your soldiers at the outpost.",
"The enemy defeated your soldiers at the patrol post.",
"The enemy defeated your soldiers at the sentinel.",
"The enemy defeated your soldiers at the sentry.",
"The enemy defeated your soldiers at the small tower.",
"The enemy defeated your soldiers at the tower.",
"The enemy defeated your soldiers at the treetop sentry.",
"The enemy defeated your soldiers at the warriors’ dwelling.",
"The enemy defeated your soldiers at the wooden tower.",
"The farmer working at this farm has no cleared soil to plant his seeds.",
"The fishing grounds are full",
"The inhabitants of the rough North Sea shore.",
"The mighty tribes of the east-lands.",
"The Widelands Development Team",
"This is the culture of the Roman Empire.",
"Thor",
"Thron",
"Thyrrenia",
"Tiberius",
"Tiger Eye",
"Tips",
"Titus",
"Tobago",
"Tonantins",
"Toolsmith",
"Toolsmithy",
"Toototobi",
"Topaz",
"Tortuga",
"Tourmaline",
"Tower",
"Trading Outpost",
"Traianus",
"Trainer",
"Training Arena",
"Training Camp",
"Training Glade",
"Traira",
"Treetop Sentry",
"Tribal Encyclopedia",
"Trinidad",
"Tumiã",
"Tunic",
"Tupana",
"Uaicurapa",
"Uarini",
"Uatumã",
"Uaupés",
"Ullr",
"Umari",
"Uneiuxi",
"Unini",
"upgrading soldier attack from level 0 to level 1",
"upgrading soldier attack from level 1 to level 2",
"upgrading soldier attack from level 2 to level 3",
"upgrading soldier attack from level 3 to level 4",
"upgrading soldier attack from level 4 to level 5",
"upgrading soldier attack from level 5 to level 6",
"upgrading soldier defense from level 0 to level 1",
"upgrading soldier defense from level 1 to level 2",
"upgrading soldier evade from level 0 to level 1",
"upgrading soldier evade from level 1 to level 2",
"upgrading soldier evade from level 2 to level 3",
"upgrading soldier health from level 0 to level 1",
"upgrading soldier health from level 1 to level 2",
"upgrading soldier health from level 2 to level 3",
"upgrading soldier health from level 3 to level 4",
"Uruá",
"Urubaxi",
"Urubu",
"Urucu",
"Urupadi",
"Uthlande",
"Valdar",
"Venus",
"Vespasianus",
"Vesta",
"Vili",
"Village",
"Vinea",
"Vine Farmer",
"Vineyard",
"Vintner",
"Vitellius",
"Volf",
"Warehouse",
"Wares",
"Warhelm",
"War Mill",
"Warrior’s Ax",
"Warrior’s Coat",
"Warriors’ Dwelling",
"Warriors’ Gathering",
"War Spear",
"Water",
"Water Gatherer’s Hut",
"Weaponsmith",
"Weapon Smithy",
"Weaver",
"weaving",
"weaving cloth",
"Weaving Mill",
"weaving spidercloth",
"Well",
"Wheat",
"Wheat Field (harvested)",
"Wheat Field (medium)",
"Wheat Field (ripe)",
"Wheat Field (small)",
"Wheat Field (tiny)",
"Wild Boar",
"Wilderness Keeper",
"Wilderness Keeper’s Tent",
"Wine",
"Winery",
"Wolverine",
"Woodcutter",
"Woodcutter’s House",
"Woodcutter’s Hut",
"Wooden Helmet",
"Wooden Spear",
"Wooden Tower",
"Wood Hardener",
"Wool",
"Workers",
"working",
"Xeruã",
"Xie",
"Your barrier discovered an aggressor.",
"Your barrier is under attack.",
"Your blockhouse discovered an aggressor.",
"Your blockhouse is under attack.",
"Your castle discovered an aggressor.",
"Your castle is under attack.",
"Your citadel discovered an aggressor.",
"Your citadel is under attack.",
"Your fortification discovered an aggressor.",
"Your fortification is under attack.",
"Your fortress discovered an aggressor.",
"Your fortress is under attack.",
"Your guardhall discovered an aggressor.",
"Your guardhall is under attack.",
"Your guardhouse discovered an aggressor.",
"Your guardhouse is under attack.",
"Your high tower discovered an aggressor.",
"Your high tower is under attack.",
"Your high wooden tower discovered an aggressor.",
"Your high wooden tower is under attack.",
"Your observation tower discovered an aggressor.",
"Your observation tower is under attack.",
"Your outpost discovered an aggressor.",
"Your outpost is under attack.",
"Your patrol post discovered an aggressor.",
"Your patrol post is under attack.",
"Your sentinel discovered an aggressor.",
"Your sentinel is under attack.",
"Your sentry discovered an aggressor.",
"Your sentry is under attack.",
"Your small tower discovered an aggressor.",
"Your small tower is under attack.",
"Your soldiers defeated the enemy at the barrier.",
"Your soldiers defeated the enemy at the blockhouse.",
"Your soldiers defeated the enemy at the castle.",
"Your soldiers defeated the enemy at the citadel.",
"Your soldiers defeated the enemy at the fortification.",
"Your soldiers defeated the enemy at the fortress.",
"Your soldiers defeated the enemy at the guardhall.",
"Your soldiers defeated the enemy at the guardhouse.",
"Your soldiers defeated the enemy at the high tower.",
"Your soldiers defeated the enemy at the high wooden tower.",
"Your soldiers defeated the enemy at the observation tower.",
"Your soldiers defeated the enemy at the outpost.",
"Your soldiers defeated the enemy at the patrol post.",
"Your soldiers defeated the enemy at the sentinel.",
"Your soldiers defeated the enemy at the sentry.",
"Your soldiers defeated the enemy at the small tower.",
"Your soldiers defeated the enemy at the tower.",
"Your soldiers defeated the enemy at the treetop sentry.",
"Your soldiers defeated the enemy at the warriors’ dwelling.",
"Your soldiers defeated the enemy at the wooden tower.",
"Your soldiers have occupied your barrier.",
"Your soldiers have occupied your blockhouse.",
"Your soldiers have occupied your castle.",
"Your soldiers have occupied your citadel.",
"Your soldiers have occupied your fortification.",
"Your soldiers have occupied your fortress.",
"Your soldiers have occupied your guardhall.",
"Your soldiers have occupied your guardhouse.",
"Your soldiers have occupied your high tower.",
"Your soldiers have occupied your high wooden tower.",
"Your soldiers have occupied your observation tower.",
"Your soldiers have occupied your outpost.",
"Your soldiers have occupied your patrol post.",
"Your soldiers have occupied your sentinel.",
"Your soldiers have occupied your sentry.",
"Your soldiers have occupied your small tower.",
"Your soldiers have occupied your tower.",
"Your soldiers have occupied your treetop sentry.",
"Your soldiers have occupied your warriors’ dwelling.",
"Your soldiers have occupied your wooden tower.",
"Your tower discovered an aggressor.",
"Your tower is under attack.",
"Your treetop sentry discovered an aggressor.",
"Your treetop sentry is under attack.",
"Your warriors’ dwelling discovered an aggressor.",
"Your warriors’ dwelling is under attack.",
"Your wooden tower discovered an aggressor.",
"Your wooden tower is under attack.",
"Yrsa",
"Zinho"
};

static const uint kNStr = const_strings.size();

#endif
