name: build - macos
on:
  workflow_call:

jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        config: [debug, release]
        compiler: [clang]
        os: [13, 14]
        # Check https://github.com/actions/runner-images#available-images
    name: MacOS ${{ matrix.os }} ${{ matrix.config }} ${{ matrix.compiler }}
    # ${{ matrix.arch }}
    runs-on: macos-${{ matrix.os }}
    env:
      # Export for build_app.sh
      MATRIX_OS: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Installing dependencies
      run: |
        export ICU_ROOT="$(brew --prefix icu4c)"
        # Suppress warnings about installing formulas instead of casks. Casks would raise another
        # warning about disabling macos gatekeeper.
        ./install-dependencies.sh homebrew --formula
        # temporary fix for macos-14 arm failures
        brew install --quiet icu4c
    - name: Building
      run: |
        mkdir build_wl
        cd build_wl/
        ../utils/macos/build_app.sh "--${{ matrix.config }}" "--${{ matrix.compiler }}"
        grep -v REVDETECT-BROKEN ../build/VERSION
        DMGPATH="$(pwd)"
        DMGFILE="$(ls *.dmg)"
        ARCH="$(uname -m)"
        DMGNEWNAME="${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}-macos${{ matrix.os }}-${ARCH}.dmg"
        echo "Found DMG file: $DMGPATH/$DMGFILE"
        echo "Moving to: $DMGNEWNAME"
        mv "$DMGFILE" "$DMGNEWNAME"
        echo "arch=$ARCH" >>"$GITHUB_ENV"
        echo "dmg_name=$DMGNEWNAME" >>"$GITHUB_ENV"
    - name: Uploading DMG
      uses: actions/upload-artifact@v4
      with:
        name: Widelands ${{ matrix.config }} ${{ matrix.compiler }} MacOS ${{ matrix.os }} ${{ env.arch }} AppImage
        path: ${{ env.dmg_name }}
