name: build - macos
on:
  workflow_call:

jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        config: [debug, release]
        compiler: [clang]
        os: [13, 14]
        # Check https://github.com/actions/runner-images#available-images
    name: MacOS ${{ matrix.os }} ${{ matrix.config }} ${{ matrix.compiler }}
    # ${{ matrix.arch }}
    runs-on: macos-${{ matrix.os }}
    steps:
    - name: Get architecture
      run: |
        echo "runner_arch=$(uname -m)" >>"$GITHUB_ENV"
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Installing dependencies
      run: |
        echo "::notice::arch: $runner_arch"
        if [ -z "$runner_arch" ] ; then exit 1 ; fi
        export ICU_ROOT="$(brew --prefix icu4c)"
        # Suppress warnings about installing formulas instead of casks. Casks would raise another
        # warning about disabling macos gatekeeper.
        ./install-dependencies.sh homebrew --formula
        # temporary fix for macos-14 arm failures
        brew install --quiet icu4c
    - name: Building
      run: |
        mkdir build_wl
        cd build_wl/
        ../utils/macos/build_app.sh "--${{ matrix.config }}" "--${{ matrix.compiler }}"
        grep -v REVDETECT-BROKEN ../build/VERSION
        DMGPATH="$(pwd)"
        DMGFILE="$(ls *.dmg)"
        echo "DMG file is: $DMGPATH/$DMGFILE"
        mv "$DMGFILE" "${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}-macos${{ matrix.os }}-${runner_arch}.dmg"

    - name: Uploading DMG
      uses: actions/upload-artifact@v4
      with:
        name: Widelands ${{ matrix.config }} ${{ matrix.compiler }} MacOS ${{ matrix.os }} ${{ env.runner_arch }} AppImage
        path: ${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.config }}-${{ matrix.compiler }}-macos${{ matrix.os }}-${{ env.runner_arch }}.dmg
